// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasTEhjIzGv4rQi8KQRf33ilA4FF0GlL0',
    appId: '1:641741299605:web:a5c604fcb26f609bdde09c',
    messagingSenderId: '641741299605',
    projectId: 'my-ecommerce-app-23-4941f',
    authDomain: 'my-ecommerce-app-23-4941f.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-23-4941f.firebasestorage.app',
    measurementId: 'G-YN6T6FVLQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKo3fkXwI7G1lET_3uVZai2QZFYwomklc',
    appId: '1:641741299605:android:f2f295237fec4e49dde09c',
    messagingSenderId: '641741299605',
    projectId: 'my-ecommerce-app-23-4941f',
    storageBucket: 'my-ecommerce-app-23-4941f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyCgihXOpzh0QZicAJrtEhF9XHrkDYWyE',
    appId: '1:641741299605:ios:a8c48a05d74a9c3ddde09c',
    messagingSenderId: '641741299605',
    projectId: 'my-ecommerce-app-23-4941f',
    storageBucket: 'my-ecommerce-app-23-4941f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyCgihXOpzh0QZicAJrtEhF9XHrkDYWyE',
    appId: '1:641741299605:ios:a8c48a05d74a9c3ddde09c',
    messagingSenderId: '641741299605',
    projectId: 'my-ecommerce-app-23-4941f',
    storageBucket: 'my-ecommerce-app-23-4941f.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBasTEhjIzGv4rQi8KQRf33ilA4FF0GlL0',
    appId: '1:641741299605:web:b01948ec6be36d70dde09c',
    messagingSenderId: '641741299605',
    projectId: 'my-ecommerce-app-23-4941f',
    authDomain: 'my-ecommerce-app-23-4941f.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-23-4941f.firebasestorage.app',
    measurementId: 'G-HP5FCHBWJZ',
  );
}
